### ISSUE TITLE
Using vertx-maven-plugin and fabric8

### ISSUE THREAD

**Issue by kameshsampath** [tsegismont/vertx-musicstore#1]
@tsegismont - just my two cents - how about using https://github.com/fabric8io/vertx-maven-plugin and fabric8 platform to run the demo - that gives some quick teaser to the users on using the maven plugin and the right microservice platform to play with via Kubernetes

**Comment by vietj** [comment]
being a microservice demo is a non goal, the focus is more on the doing a reactive web app with vertx and rxjava, let's keep things focused and simple.

**Comment by vietj** [comment]
i.e the goal is not to promote kubernetes or F8

**Comment by tsegismont** [comment]
Because I err on the side of explicit configuration of widely used plugins
:)

As for running the demo, I don't need a deployment platform, I simply start
this app from the IDE

**Comment by kameshsampath** [comment]
got it @vietj may be i did no think on that side of it :) 

@tsegismont - guys like you need to start using the new plugin to make it more popular ;) as it brings in more easiness of vert.x development, then we get some feedback to improve it

**Comment by tsegismont** [comment]
@kameshsampath if you can provide a PR for the Maven plugin part I'd be glad to review and merge it. I still want to be able to start the app from IDE without going through Maven builds, that's my only criteria.

**Comment by kameshsampath** [comment]
sure thing @tsegismont , am right now in middle of a feature enhancement of the plugin will complete that and send you a PR :). thanks for considering to use the plugin

**Comment by kameshsampath** [comment]
@tsegismont this should have taken this long ;) you can review and merge the https://github.com/tsegismont/vertx-musicstore/pull/5

**Comment by tsegismont** [comment]
Closed via #5 

Thanks @kameshsampath !
